--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/libEco
build-by-default: true
branches:
- stable
projects:
  libEco:
    path: ""
    model: virion
    type: library
...
